### PR TITLE
Reorganized dependencies

### PR DESCRIPTION
**Pull request by ngc92**
moves dependencies into their own directories and modernized cmake

Contrary to #48, this, for now, only changed the dependencies we use. I've not considered `raknet` an external dependency here, because I think the version we use is heavily modified by now. The dependencies are now used inside cmake as (imported) targets, instead of directly supplying compiler/linker flags, which follows a more modern cmake style.

Q: Should we also include `physfs` as part of the source code, like we do for `tinyxml` and `lua`? This would reduce one more thing to worry about when someone else is trying to build this, or in situations when there is no `dev` package, e.g. in our android tests. In #48, I've used a git submodule, but I'm not sure if that is a good solution.

### CODE REVIEW

**Review by danielknobe — COMMENTED** [review]
Some indentations have changed back to tabs. For the cmake files we currently have no rule, it should just be consistent. Everything else looks good.

**Comment by ngc92** [comment]
any thoughts on whether we should include physfs the same way we do lua and tinyxml?

**Comment by danielknobe** [comment]
Yes. In my opinion we should not do that. So far, I have liked the fact that we have used the system's libraries. How about the other way around (use tinyxml and lua from system instead of delivering it)?

**Comment by ngc92** [comment]
Let's avoid submodules, then.
I think for `lua`, we actually slightly modify things in that we don't even compile the `os` library functions. At least there are some commented-out files in the cmake. 

At the very least, it would make sense to compile these as dynamic libraries instead of statically linking, so that system libraries can be used when we want to.

I still see an advantage in making the build process as simple as possible, especially when there is no package manager easily available. It would also make it easier to put some pre-built binaries up on github that should run without being installed.

**Comment by ngc92** [comment]
i've opened an issue so this does not get lost after the PR is merged.

**Pull request merged**
